# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1ee479f9c5fd8d6a32cfee112142f67a6d7bba9f98e20ef3c37f08dbd5b78ccbcee889657a4ada5e10ecccbe89cc4a9c49e2810e50c8b13bce16072034cad8

test:
  secret_key_base: c832e81ad6e9dc3192cfbe1be59105b7032af6778f98555aea9ff606e7d8f092d0b28f11e8d60537345c408638425cff050f08d9c3c48eb51674c54b0bf50816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
